### ISSUE TITLE
MeetupKey.json is no longer needed?

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/aura#1]
With https://github.com/gdg-x/aura/blob/master/src/config/key.js, it looks like https://github.com/gdg-x/aura/blob/master/src/assets/data/MeetupKey.json is no longer needed or used?

**Comment by Vrijraj** [comment]
There is no use of MeetupKey.json file.
MeetupKey.json file has removed from https://github.com/gdg-x/aura/blob/master/src/assets/data/MeetupKey.json
