### ISSUE TITLE
Upgrading to Vuetify 2

### ISSUE THREAD

**Issue by nimitbhargava** [gdg-x/aura#23]
**Is your feature request related to a problem? Please describe.**
Current Vuetify version is `v1.5.2`
Latest being v2.0

**Describe the solution you'd like**
It would require to upgrade the project to use v2.0
Upgrade guide [here](https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0)

**Describe alternatives you've considered**
We have to follow the [upgrade guide](https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0)

**Comment by Vrijraj** [comment]
Yes, I'm working on Vuetify 2

**Comment by nimitbhargava** [comment]
@Vrijraj 
I am open to help. Please let me know if I can help in some way.

**Comment by aaronlippold** [comment]
Any updates on the Vuetify 2 conversion?

**Comment by Vrijraj** [comment]
Yes, Right now in the developing phase, I'm adding lots of new features like Dark theme mode, Custom Events Routing, Blog, Showcase page...
Link: https://aura-gdg.web.app/

Thanks for asking @aaronlippold

**Comment by aaronlippold** [comment]
Hello, that looks great. I have a set of projects right now which I would
like to use this template for, if you wouldn't mind. Would I be able to
poke around the repo? I would be happy to have my team help you as I am
trying to standardize our project sites.

If you don't mind I'm happy to fork the repo and start pushing up a few
things.

Are you using TypeScript? Vuex?

Thanks

Aaron

**Comment by aaronlippold** [comment]
We are hoping to have a couple of the sites up in the next couple of weeks
so I'm sure we could help move things along if that's acceptable.

Look forward to hearing from you

Aaron

**Comment by aaronlippold** [comment]
Feel free to check some of our vue development at
www.github.com/mitre/heimdall-lite.

**Comment by aaronlippold** [comment]
@Vrijraj can we help with the 2.0 development?

**Comment by Vrijraj** [comment]
Yeah, we'll be happy for your contribution. Please share your contact email id.

**Comment by nimitbhargava** [comment]
@Vrijraj 
Please feel free to contact me as well related to 2.0 development. 
You can send dm at [@nimitbhargava](https://twitter.com/NimitBhargava)

**Comment by aaronlippold** [comment]
Hi,

Email sent.

Aaron
--------
Aaron Lippold

lippold@gmail.com

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by aaronlippold** [comment]
> Yeah, we'll be happy for your contribution. Please share your contact email id.

Hi, my github handle is 'aaronlippold' and my email is lippold@gmail.com.

**Comment by atharvaunde59** [comment]
Hello @Vrijraj,
Vuetify 2 version looks 🔥 
May I use it for my TEDx event? if you don't mind? 
I also found 'team' folder is missing in /assets/img  in Vuetify2 build

**Comment by Vrijraj** [comment]
Hi Everyone!

Right now I'm in Sri Lanka for my Talk, will be available on December 1st
week. And I'll contact you on that time.

Sorry for inconvenience.

**Comment by Vrijraj** [comment]
> Hello @Vrijraj,
> Vuetify 2 version looks 🔥
> May I use it for my TEDx event? if you don't mind?
> I also found 'team' folder is missing in /assets/img in Vuetify2 build

@atharvaunde59 Yes, you can but right now it is in the development phase. We're trying hard to release this one by dec last week.
