### ISSUE TITLE
When click on event title on top toolbar, user not taken to homepage

### ISSUE THREAD

**Issue by nimitbhargava** [gdg-x/aura#24]
When click on event title on top toolbar, user not taken to homepage
Is this expected?

**Comment by nimitbhargava** [comment]
If this is not expected then I can create PR for it.

**Comment by Vrijraj** [comment]
Thanks @nimitbhargava, you can create PR

**Comment by nimitbhargava** [comment]
I will work on the PR

**Comment by Vrijraj** [comment]
Done by @nimitbhargava
