### ISSUE TITLE
Null / missing data for components

### ISSUE THREAD

**Issue by aaronlippold** [gdg-x/aura#36]
When a component - such as an event - does not have the full data - the component should still render. At the moment, when data is missing the site fails to compile. 

If possible allow for missing data, especially on things that could reasonably not be needed - such as a physical location or map data for a fully online event.

**Comment by bharatagsrwal** [comment]
Thanks for showing your interest.
As I am working with @Vrijraj on that and in upcoming updates we will fix this issue.
As we are looking for your contribution so that we can build better aura.

**Comment by aaronlippold** [comment]
Hi. Does it make more sense to move this into the version 2 work or should
we update both this repo and the vue2 version?

I don't yet have access to the V2 repo. If you could add me to the repo I
can fork and push up updates.

Thanks

Aaron
