### ISSUE TITLE
Expand Code of Conduct on About page

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/aura#4]
Boomerang has a pretty extensive CoC that could be used/referenced.

The template can be found [here](https://github.com/gdg-x/boomerang/blob/master/app/conduct/conduct.html).

An example can be found [here](http://gdg-x.github.io/boomerang/#!/conduct).

**Comment by Vrijraj** [comment]
CoC updated 
https://github.com/gdg-x/aura/blob/master/src/components/about/AntiHarassmentPolicy.vue

Thanks for the example
