### ISSUE TITLE
[Admin] Manage Team Page 

### ISSUE THREAD

**Issue by Vrijraj** [gdg-x/aura#54]
Adamin can
1. Manage the Team data (CURD)
2. Manage the status of the team and profile url for team 
.../team/vrijraj_singh

**Comment by atharvaunde59** [comment]
Hello @Vrijraj  how to make Team Members added in cloud store available on the teams page that that it wont get fetched from .json file but will be using cloudstore data as database?

**Comment by Vrijraj** [comment]
@atharvaunde59  Issue is resolved in Aura v3 (https://github.com/gdg-x/aura) & Aura Admin (https://github.com/gdg-x/aura-admin)
