### ISSUE TITLE
Make seasonal feature component customizable

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/aura#6]
Currently https://github.com/gdg-x/aura/blob/master/src/components/home/wtmInfo.vue is hard coded to feature WTM. But every few months there is another seasonal feature like Cloud NEXT Extended, I/O Extended, DevFest, etc. It should be possible to define the text and image for this component in a config file so that the featured seasonal activity could be updated easily.

**Comment by Vrijraj** [comment]
![Feature Event Component](https://user-images.githubusercontent.com/10599101/54192154-566dac00-44dd-11e9-9798-b503b34ec77b.PNG)

Customizable seasonal feature component Added
https://github.com/gdg-x/aura/blob/master/src/components/home/featureEvent.vue

**Comment by Vrijraj** [comment]
and its JSON File 
https://github.com/gdg-x/aura/blob/master/src/assets/data/featureEvent.json

And Making its Admin Pannel 
![Screenshot (83)](https://user-images.githubusercontent.com/10599101/54192817-d34d5580-44de-11e9-8e67-3ca838e78adc.png)
![Screenshot (84)](https://user-images.githubusercontent.com/10599101/54192823-d5afaf80-44de-11e9-88b8-f12809dde0bb.png)
![Screenshot (85)](https://user-images.githubusercontent.com/10599101/54192825-d6484600-44de-11e9-9d1f-b134cad3aeef.png)
![Screenshot (184)](https://user-images.githubusercontent.com/10599101/54193356-e3b20000-44df-11e9-8df8-6d7bbc86f10b.png)
![Screenshot (185)](https://user-images.githubusercontent.com/10599101/54193361-e6145a00-44df-11e9-9b56-3c62e0284f8f.png)

**Comment by Splaktar** [comment]
Very cool! Thanks

**Comment by Vrijraj** [comment]
@Splaktar Time and Date format updated
https://github.com/gdg-x/aura/blob/master/src/assets/data/featureEvent.json

Also, I've added Google Map Link

**Comment by Splaktar** [comment]
Nice. Please let me know when I can check it out on https://aura-client-master.firebaseapp.com/

**Comment by Vrijraj** [comment]
Its live right now

**Comment by Splaktar** [comment]
Looks good!
