### ISSUE TITLE
Documentation: Admin Panel User Setup

### ISSUE THREAD

**Issue by atharvaunde59** [gdg-x/aura#61]
Documentation needs to be updated about the creation of users to access the admin panel for the purpose of managing team members, speakers, insight analysis, push notification triggering.

**Comment by bharatagsrwal** [comment]
Thanks @atharvaunde59 for your constant support. Rite now our Aura team is working on admin panel functionality and it's documentation, admin panel is under development, we are trying to complete it as soon as possible and when it will done we will notify you. 
Thanks

**Comment by Vrijraj** [comment]
@atharvaunde59  Issue is resolved in Aura v3 (https://github.com/gdg-x/aura) & Aura Admin (https://github.com/gdg-x/aura-admin)
