### ISSUE TITLE
Cloud Messaging Error

### ISSUE THREAD

**Issue by atharvaunde59** [gdg-x/aura#65]
`FirebaseError: Messaging: We are unable to register the default service worker. Failed to register a ServiceWorker for scope ('http://localhost:8080/firebase-cloud-messaging-push-scope') with script ('http://localhost:8080/firebase-messaging-sw.js'): The script has an unsupported MIME type ('text/html'). (messaging/failed-serviceworker-registration).`

I cloned the devv#2 branch and added my firebase config to it. All other firebase services like admin login, firestore is working but FCM is not generating token when i try to click on bell icon.
It gives above error. I have generated server key and added it to the notification,vue file's script but still something is broken.
Am I missing something?

**Comment by bharatagsrwal** [comment]
On development server (`npm run serve`), vue does not register service worker, so try in production server (`npm run build`) and then use a webserver to serve those dist folders files, after that your service worker will get register.
Regards

**Comment by atharvaunde59** [comment]
Thanks a lot! I was testing on npm run serve😅
