### ISSUE TITLE
Unable to render upcoming events

### ISSUE THREAD

**Issue by Snickdx** [gdg-x/aura#75]
**Describe the bug**
Vue error "Cannot read property 'name' of undefined" on upcoming events page.

**To Reproduce**
Visit https://gdgpos.com/events

**Expected behavior**
Should render upcoming wtm and study jam event.
[WTM Event Meetup](wtm.gdgpos.com)
[Study Jam Event Meetup](jam.gdgpos.com)
[GDG POS aura repo](https://github.com/gdgpos/aura)

**Screenshots**
Stack trace on Dev Server
![image](https://user-images.githubusercontent.com/5845054/76980757-fbe90600-690f-11ea-856e-903bb3124376.png)

Network tab in dev tools
![image](https://user-images.githubusercontent.com/5845054/76980910-2dfa6800-6910-11ea-81e2-260463e04323.png)

**Desktop:**

**Comment by Vrijraj** [comment]
@Snickdx Issue is resolved in Aura v3 (https://github.com/gdg-x/aura)
